# Generated by Django 5.2.4 on 2025-08-20 00:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Format: 'Couple NOM1-NOM2'", max_length=100, unique=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('adresse_couple', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Couple',
                'verbose_name_plural': 'Couples',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20)),
                ('date_adhesion', models.DateField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='AppTontine.couple')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Tontine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2024)])),
                ('nom', models.CharField(default='Tontine Annuelle', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField(editable=False)),
                ('date_fin', models.DateField(editable=False)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tontines_crees', to='AppTontine.membre')),
            ],
            options={
                'verbose_name': 'Tontine',
                'verbose_name_plural': 'Tontines',
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='ReceptionTontine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('montant_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('montant_membre1', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('montant_membre2', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('date_reception', models.DateField()),
                ('est_confirme', models.BooleanField(default=False)),
                ('couple_beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='AppTontine.couple')),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='AppTontine.tontine')),
            ],
            options={
                'verbose_name': 'Réception',
                'verbose_name_plural': 'Réceptions',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre_reception', models.PositiveIntegerField(help_text='Mois attribué (1=janvier, 12=décembre)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='AppTontine.couple')),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='AppTontine.tontine')),
            ],
            options={
                'verbose_name': 'Attribution',
                'verbose_name_plural': 'Attributions',
                'ordering': ['tontine', 'ordre_reception'],
            },
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('montant_membre1', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_membre2', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_paiement', models.DateField()),
                ('est_valide', models.BooleanField(default=False)),
                ('couple_beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations_recues', to='AppTontine.couple')),
                ('payeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations_payees', to='AppTontine.membre')),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='AppTontine.tontine')),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
            },
        ),
        migrations.AddConstraint(
            model_name='membre',
            constraint=models.UniqueConstraint(condition=models.Q(('couple__isnull', False)), fields=('couple',), name='max_2_membres_par_couple'),
        ),
        migrations.AlterUniqueTogether(
            name='receptiontontine',
            unique_together={('tontine', 'mois')},
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('tontine', 'couple'), ('tontine', 'ordre_reception')},
        ),
        migrations.AlterUniqueTogether(
            name='cotisation',
            unique_together={('tontine', 'mois', 'payeur', 'couple_beneficiaire')},
        ),
    ]
