# Generated by Django 5.2.4 on 2025-08-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTontine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='nom',
            field=models.CharField(help_text="Format: 'Couple NOM1_MARI-NOM2_FEMME'", max_length=100, unique=True),
        ),
    ]
