# Generated by Django 5.2.4 on 2025-08-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTontine', '0002_alter_couple_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisation',
            name='date_paiement',
            field=models.DateField(auto_now_add=True),
        ),
    ]
