# Generated by Django 5.2.4 on 2025-09-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTontine', '0003_alter_cotisation_date_paiement'),
    ]

    operations = [
    ]
