# Generated by Django 5.2.4 on 2025-09-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTontine', '0004_auto_20250907_1118'),
    ]

    operations = [
    ]
