# Generated by Django 5.2.4 on 2025-09-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTontine', '0005_auto_20250907_1126'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membre',
            name='max_2_membres_par_couple',
        ),
    ]
